server:
  port: 8081

spring:
  application:
    name: orchestrator-worker
  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/scheduler
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 5
        max-concurrency: 20
        acknowledge-mode: manual

worker:
  connect-timeout-ms: 5000
  read-timeout-ms: 10000
